name = "uyan-kenantomm"
main = "token_proxy.js"
compatibility_date = "2024-01-01"
account_id = "efda302cd88170229cb0d3156b1406e7"  # Sizin hesap ID'niz
workers_dev = true

[env.production]
name = "uyan-kenantomm"
